name: github pages
on:
  push:
    branches:
      - main
    paths:
      - trees/**
      - assets/**
      - .github/workflows/publish.yml
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1"

      - name: Install Forester
        run: |
          git clone https://git.sr.ht/~jonsterling/ocaml-forester
          cd ocaml-forester
          opam pin add -y . --locked

      - name: "build forester"
        run: make release

      - name: "Deploy"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
